### ISSUE TITLE
UB revolving around `std::slice::from_raw_parts`

### ISSUE THREAD

**Issue by marc0246** [simplerr/rust-renderer#6]
Hi! I was strolling through looking for inspiration, and you have a very nice project going on!

While doing said strolling, I noticed a couple uses of `std::slice::from_raw_parts` that convert a `&[T] where T: Copy` to a `&[u8]`. Referencing [the safety docs of `from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety): point 1, 3 and 4 are covered because the source is a reference and you're converting to bytes, but point 2 is not covered. `T` might have padding, in which case not all bytes will be properly initialized, leading to UB.

On an unrelated note: I also noticed some uses of `std::slice::from_raw_parts` to construct a one-element slice. I think you're looking for [`std::slice::from_ref`](https://doc.rust-lang.org/std/slice/fn.from_ref.html), which does that without needing unsafe.

**Comment by simplerr** [comment]
Thanks a lot for taking a look at the project and after noticing this issue coming up with something that looks like a great improvement! :grinning:

I investigated a bit how they do similar things in the `wgpu` project and they seem to use the `bytemuck` crate and derive the Pod and Zeroable traits for structs uploaded to uniform buffers for example. From my understanding doing this you get a compile time error if the struct contains padding bytes which is nice. Perhaps combining that after merging your changes would be a robust solution.

Using ptr::copy_nonoverlapping and MaybeUninit also seems nice!

I'll test this and get back with feedback after the weekend 👍

**Comment by simplerr** [comment]
Forcing users to derive `Pod` and not allow padding due to having `T: Pod` in the public API is a good point and not something I want to do right now. One option would be to change the API to take &[u8] instead of &[T] and leave it completely up to the user which method they use to get the &[u8], but I like the ease-of-use by handling that inside the API which makes user code simpler.

Skipping `bytemuck` for now :)
